journal/urls.py
from django.contrib import admin
from django.urls import path
from journal.views import home, add_resource, delete_resource, profile

app_name = 'journal'

urlpatterns = [
    path('', home, name='home'),
    path('new_resource', add_resource, name='new_resource'),
    path('delete_resource', delete_resource, name='delete_resource'),
    path('profile', profile, name='profile'),
    path('new_resource/<int:resource_id>/', add_resource, name='new_resource'),
    path('delete_resource/<int:resource_id>/', delete_resource, name='delete_resource'),
    path('profile', profile, name='profile'),

]

learnjournal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('journal.urls', namespace='journal')),

]

from django.conf import settings
from django.conf.urls.static import static

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

journal/models.py
from django.db import models


class Resource(models.Model):
    Name = models.CharField(max_length=50)
    Link = models.URLField()

journal/forms.py
from django.forms import ModelForm
from journal.models import Resource


class ResourceForm(ModelForm):
    class Meta:
        model = Resource
        fields = ['Name', 'Link']

journal/views.py
from django.http import HttpResponse
from django.shortcuts import render
from journal.models import Resource
from django.template import loader
from journal.forms import ResourceForm
from django.shortcuts import redirect


# Create your views here.
def home(request):
    resources = Resource.objects.all()
    return render(request, 'home.html', {
        'journal_resource': resources
    })


def add_resource(request, resource_id=None):
    if resource_id:
        main_message = 'Update resource'
        resource = Resource.objects.get(id=resource_id)
    else:
        main_message = 'Create new resource'
    if request.method == 'POST':
        if resource_id:
            resource_form = ResourceForm(request.POST, instance=resource)
        else:
            resource_form = ResourceForm(request.POST)
        resource_form.save()
        return redirect('journal:home')
    else:
        if resource_id:
            resource_form = ResourceForm(instance=resource)
        else:
            resource_form = ResourceForm()
    return render(request, 'new_resource.html', {
        'resource_form': resource_form,
        'main_message': main_message
    })


def delete_resource(request, resource_id=None):
    if resource_id:
        main_message = 'Delete resource'
        resource = Resource.objects.get(pk=resource_id)
    else:
        return redirect('journal:home')
    if request.method == 'POST':
        if resource_id:
            resource_form = ResourceForm(request.POST, instance=resource)
        else:
            resource_form = ResourceForm(request.POST)
        resource.delete()
        return redirect('journal:home')
    else:
        if resource_id:
            resource_form = ResourceForm(instance=resource)
        else:
            resource_form = ResourceForm()
    return render(request, 'delete_resource.html', {
        'resource_form': resource_form,
        'main_message': main_message
    })


def profile(request):
    return render(request, 'profile.html')

journal/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <script src="https://kit.fontawesome.com/b254266fe9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Journal App</title>
</head>

{% block navbar %}
<nav class="navbar sticky-top navbar-light bg-white shadow-sm p-3 mb-5 bg-white rounded">
    <a class="navbar-brand mb-0 h1" href="{% url 'journal:home' %}">
      <img src="{% static 'admin/img/solirius_logo.png' %}" width="150" height="50" alt="logo">Journal App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'journal:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'journal:new_resource' %}">Create new resource</a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="{% url 'journal:delete_resource' %}">Delete resource</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>

  <div>
    <form class="form-inline">
        <button class="btn shadow-none">
        <a href="{% url 'journal:profile' %}"<i class="fa-regular fa-user fa-xl" type="button"></i></a>
        </button>
    </form>
  </div>
</nav>
{% endblock navbar %}

<body>
{% block content %}

{% endblock content %}
</body>
</html>

journal/templates/delete_resource.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{{ main_message }}

<form method="POST">
    <div class="form-group">
    {% csrf_token %}
    {{ resource_form }}
    <input type='Submit' value='{{ main_message }}'/>
    </div>
</form>

{% endblock %}

journal/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<table class="table table-bordered">
   <thead>
     <tr>
        <th scope="col">Name</th>
        <th scope="col">Link</th>
        <th scope="col"> </th>
    </tr>
   </thead>
    {% for res in journal_resource %}
    <tr>
        <td>{{ res.Name }}</td>
        <td><a href='{{ res.Link }}'>{{ res.Link }}</a></td>
        <td><a href="{% url 'journal:new_resource' res.id%}">Edit</a></td>
        <td><a href="{% url 'journal:delete_resource' res.id%}">Delete</a></td>
    </tr>
    {% endfor %}
</table>

<button type="button" class="btn btn-outline-primary"><a href="{% url 'journal:new_resource' %}">Create new resource here</a>
</button>

{% endblock content %}

journal/templates/new_resource.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{{ main_message }}

<form method="POST">
    <div class="form-group">
    {% csrf_token %}
    {{ resource_form }}
    <input type='Submit' value='{{ main_message }}'/>
    </div>
</form>

{% endblock %}

journal/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{{ main_message }}

profile

{% endblock %}